[features]
seeds = false
skip-lint = false
[programs.localnet]
deposit = "4w6FdDYH1uBrPh4DSY6xwU7rT85bDYeWrX9xRCCVaoLX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/bhaskarkh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
